apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  ## NOTE: this ensures Namespaces are not deleted or pruned by ArgoCD (users can still delete them manually)
  argocd.argoproj.io/sync-options: Delete=false,Prune=false
resources:
  ###########################
  ## deploykf-dependencies ##
  ###########################
  - deploykf-dependencies/istio.yaml

  ###################
  ## deploykf-core ##
  ###################
  - deploykf-core/deploykf-auth.yaml
  - deploykf-core/deploykf-dashboard.yaml
  - deploykf-core/deploykf-istio-gateway.yaml

  ##################
  ## deploykf-opt ##
  ##################
  - deploykf-opt/deploykf-mysql.yaml

  ####################
  ## deploykf-tools ##
  ####################
  ## TODO: add 'deploykf-tools' https://www.deploykf.org/reference/future-tools/

  ###########################
  ## kubeflow-dependencies ##
  ###########################
  - kubeflow-dependencies/kubeflow-argo-workflows.yaml

  ####################
  ## kubeflow-tools ##
  ####################
  - kubeflow-tools/kubeflow.yaml