
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kf-tools--tensorboards--tensorboard-controller
  namespace: "argocd"
  annotations:
    ## applications in 'kubeflow-tools' come after 'kubeflow-dependencies'
    argocd.argoproj.io/sync-wave: "60"
  labels:
    app.kubernetes.io/name: tensorboard-controller
    app.kubernetes.io/component: kubeflow-tools
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/wbe7/codesense.git"
    targetRevision: "main"
    path: "infra/deploykf/manifests/manifests/kubeflow-tools/tensorboards/tensorboard-controller"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeflow