apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  ###########################
  ## deploykf-dependencies ##
  ###########################
  - deploykf-dependencies/istio.yaml
  - deploykf-dependencies/kyverno.yaml

  ###################
  ## deploykf-core ##
  ###################
  - deploykf-core/deploykf-auth.yaml
  - deploykf-core/deploykf-dashboard.yaml
  - deploykf-core/deploykf-istio-gateway.yaml
  - deploykf-core/deploykf-profiles-generator.yaml

  ##################
  ## deploykf-opt ##
  ##################
  - deploykf-opt/deploykf-mysql.yaml

  ####################
  ## deploykf-tools ##
  ####################
  ## TODO: add 'deploykf-tools' https://www.deploykf.org/reference/future-tools/

  ###########################
  ## kubeflow-dependencies ##
  ###########################
  - kubeflow-dependencies/kubeflow-argo-workflows.yaml

  ####################
  ## kubeflow-tools ##
  ####################
  - kubeflow-tools/katib.yaml
  - kubeflow-tools/notebooks--jupyter-web-app.yaml
  - kubeflow-tools/notebooks--notebook-controller.yaml
  - kubeflow-tools/pipelines.yaml
  - kubeflow-tools/poddefaults-webhook.yaml
  - kubeflow-tools/tensorboards--tensorboard-controller.yaml
  - kubeflow-tools/tensorboards--tensorboards-web-app.yaml
  - kubeflow-tools/training-operator.yaml
  - kubeflow-tools/volumes--volumes-web-app.yaml