spawnerFormDefaults:
  affinityConfig:
    options: []
    readOnly: false
    value: ""
  allowCustomImage: true
  configurations:
    readOnly: false
    value: []
  cpu:
    limitFactor: "1.2"
    readOnly: false
    value: "0.5"
  dataVolumes:
    readOnly: false
    value: []
  gpus:
    readOnly: false
    value:
      num: none
      vendor: ""
      vendors:
        - default: true
          limit: nvidia.com/gpu
          name: NVIDIA
  hideRegistry: true
  hideTag: false
  image:
    options:
      - kubeflownotebookswg/jupyter-scipy:v1.8.0
      - kubeflownotebookswg/jupyter-pytorch-full:v1.8.0
      - kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.8.0
      - kubeflownotebookswg/jupyter-tensorflow-full:v1.8.0
      - kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.8.0
    value: kubeflownotebookswg/jupyter-scipy:v1.8.0
  imageGroupOne:
    options:
      - kubeflownotebookswg/codeserver-python:v1.8.0
    value: kubeflownotebookswg/codeserver-python:v1.8.0
  imageGroupTwo:
    options:
      - kubeflownotebookswg/rstudio-tidyverse:v1.8.0
    value: kubeflownotebookswg/rstudio-tidyverse:v1.8.0
  imagePullPolicy:
    readOnly: false
    value: IfNotPresent
  memory:
    limitFactor: "1.2"
    readOnly: false
    value: 1.0Gi
  shm:
    readOnly: false
    value: true
  tolerationGroup:
    options: []
    readOnly: false
    value: ""
  tolerations:
    value:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
  workspaceVolume:
    readOnly: false
    value:
      mount: /home/jovyan
      newPvc:
        metadata:
          name: '{notebook-name}-workspace'
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
