########################################
## SHARED | deploykf-helpers
########################################
deployKF_helpers:
  deploykf_profiles:
    users_id_mapping: {"admin-user":{"email":"admin@skeaper.tech","id":"admin-user"}}
    profiles_users_access_mapping: {"team-1":{},"team-1-prod":{"admin-user":{"notebooksAccess":true,"role":"edit"}}}
    users_profiles_access_mapping: {"admin-user":{"team-1-prod":{"notebooksAccess":true,"role":"edit"}}}

  kubeflow:
    pipelines:
      object_store:
        profile:
          cloned_secret_name: "cloned--pipelines-object-store-auth"

########################################
## SHARED | deploykf
########################################
deployKF:
  extraManifests:

  clusterDomain: cluster.local

  argoWorkflows:
    enabled: true
    namespace: "kubeflow-argo-workflows"

  kubeflow:
    useridHeader: kubeflow-userid

    pipelines:
      enabled: true
      pipelineUI:
        namespace: kubeflow
        serviceAccount: ml-pipeline-ui

  gateway:
    namespace: "deploykf-istio-gateway"
    serviceAccount: "deploykf-gateway"
    emailToLowercase: false


########################################
## CONFIGS | profiles
########################################

## profile defaults
##
profileDefaults:

  ## a common prefix to add to all profile names
  ##
  profileNamePrefix: ""

  ## the default email to set as the owner of profiles
  ##
  ownerEmail: "admin@example.com"

  ## the default access for members of profiles, when not explicitly specified
  ##
  memberAccess:

    ## the Kubernetes RBAC role to bind to users in the profile namespace
    ##  - "edit": binds "ClusterRole/kubeflow-edit" (can view/create/delete resources)
    ##  - "view": binds "ClusterRole/kubeflow-view" (cam view resources)
    ##
    role: "view"

    ## if the user can ~connect~ to kubeflow notebooks in the profile
    ##
    notebooksAccess: false

  ## the default list of plugins for profiles, when not explicitly specified
  ##
  plugins: []

  ## the default resource quota for profiles, when not explicitly specified
  ##  - spec for ResourceQuotaSpec:
  ##    https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#resourcequotaspec-v1-core
  ##
  resourceQuotaSpec: {}

## user entities
##  - a list of users that can be referenced when defining profile members
##
users: [{"email":"admin@skeaper.tech","id":"admin-user"}]

## group entities
##  - a list of groups that can be referenced when defining profile members
##
groups: [{"id":"team-1--admins","users":["admin-user"]},{"id":"team-1--users","users":[]}]

## profile definitions
##  - a list of profile definitions to be generated
##
profiles: [{"members":[{"access":{"notebooksAccess":true,"role":"edit"},"group":"team-1--users"}],"name":"team-1"},{"members":[{"access":{"notebooksAccess":true,"role":"edit"},"group":"team-1--admins"},{"access":{"notebooksAccess":false,"role":"view"},"group":"team-1--users"}],"name":"team-1-prod"}]
