
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "deploykf-app-of-apps"
  namespace: "argocd"
  labels:
    app.kubernetes.io/name: deploykf-app-of-apps
    app.kubernetes.io/part-of: "deploykf"
spec:
  project: "default"
  source:
    repoURL: "https://github.com/wbe7/codesense.git"
    targetRevision: "main"
    path: "infra/deploykf/manifests/argocd"
  destination:
    ## NOTE: even if the internal apps target a remote cluster, the apps themselves should be in the Argo CD cluster
    server: "https://kubernetes.default.svc"
    namespace: "argocd"