apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: fix-clone-pipelines-object-store-auth
spec:
  generateExisting: true
  rules:
  - name: clone-pipelines-object-store-auth
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              pipelines.kubeflow.org/enabled: "true"
    generate:
      apiVersion: v1
      kind: Secret
      name: cloned--pipelines-object-store-auth
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: kubeflow
        name: deploykf-s3-credentials
