apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: patch-poddefaults-webhook-issuer
spec:
  rules:
  - name: patch-poddefaults-webhook-issuer
    match:
      any:
      - resources:
          kinds:
          - Certificate
          names:
          - admission-webhook-cert
          namespaces:
          - kubeflow
    mutate:
      patchStrategicMerge:
        spec:
          issuerRef:
            name: selfsigned
            kind: ClusterIssuer
