apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## we can't set the global namespace as we generate resources across multiple namespaces (for profiles)
## however, we must set the `configMapGenerator` namespaces to `kubeflow` to avoid this issue:
## https://github.com/kubernetes-sigs/kustomize/issues/1301#issuecomment-1308228710
#namespace: kubeflow

resources:
  ## upstream
  - upstream/manifests/kustomize/env/cert-manager/platform-agnostic-multi-user

  ## local
  - resources/profile-resources.yaml
  - resources/restart-on-pipeline-configmap-update-clusterpolicy.yaml
  - resources/clone-bucket-secret-clusterpolicy.yaml
  - resources/clone-mysql-secret-clusterpolicy.yaml

patchesStrategicMerge:
  - patches/patch-cache-server-deployment.yaml
  - patches/patch-cache-server-mutatingwebhook.yaml
  - patches/patch-metadata-grpc-deployment-deployment.yaml
  - patches/patch-metadata-grpc-virtualservice.yaml
  - patches/patch-ml-pipeline-deployment.yaml
  - patches/patch-ml-pipeline-persistenceagent-deployment.yaml
  - patches/patch-ml-pipeline-serviceaccount.yaml
  - patches/patch-ml-pipeline-ui-authorizationpolicy.yaml
  - patches/patch-ml-pipeline-ui-deployment.yaml
  - patches/patch-ml-pipeline-ui-serviceaccount.yaml
  - patches/patch-ml-pipeline-ui-virtualservice.yaml

  ## removals
  - patches/removals/argo-workflows-resources.yaml
  - patches/removals/metacontroller-resources.yaml
  - patches/removals/minio-resources.yaml
  - patches/removals/mysql-resources.yaml
  - patches/removals/profile-controller-resources.yaml

configurations:
  - params.yaml

configMapGenerator:
  - name: pipeline-install-config
    namespace: kubeflow
    behavior: merge
    literals:
      ## remove the upstream warning, because it can be confusing to users
      - warning=""

      ## ================================
      ## UserID Configs
      ## ================================
      - USERID_HEADER="kubeflow-userid"
      - USERID_PREFIX=""

      ## ================================
      ## App Configs
      ## ================================
      - appName="pipeline"
      - autoUpdatePipelineDefaultVersion="true"
      - cronScheduleTimezone="UTC"

      ## ================================
      ## Workflow Image Configs
      ## ================================
      - driverImage="ghcr.io/deploykf/kubeflow-pipelines/kfp-driver:2.1.0-deploykf.0"
      - launcherImage="ghcr.io/deploykf/kubeflow-pipelines/kfp-launcher:2.1.0-deploykf.0"

      ## ================================
      ## Cache Configs
      ## ================================
      - cacheImage="gcr.io/google-containers/busybox:1.27"
      - cacheNodeRestrictions="false"
      - MAXIMUM_CACHE_STALENESS=""
      - DEFAULT_CACHE_STALENESS=""

      ## ================================
      ## Bucket Configs
      ## ================================
      - bucketName="kubeflow-pipelines"
      - bucketRegion=""
      ## NOTE: this is not actually used in our manifests to create `ConfigMap/kfp-launcher`
      ##       as we have replaced the "kubeflow-pipelines-profile-controller" with explicitly
      ##       generated resource templates in `resources/profile-resources.yaml`
      - defaultPipelineRoot=""

      ## ================================
      ## Object Store Configs
      ## ================================
      - bucketSecure="false"
      - bucketHost="192.168.77.7"
      - bucketPort="9000"
      - bucketEndpoint="192.168.77.7:9000"

      ## ================================
      ## MySQL Configs
      ## ================================
      - ConMaxLifeTime="120s"
      - dbType="mysql"
      - mysqlHost="deploykf-mysql.deploykf-mysql.svc.cluster.local"
      - mysqlPort="3306"
      - cacheDb="kfp_cache"
      - mlmdDb="kfp_metadata"
      - pipelineDb="kfp_pipelines"

      ## ================================
      ## MySQL Configs (Legacy)
      ## ================================
      - dbHost="deploykf-mysql.deploykf-mysql.svc.cluster.local"
      - dbPort="3306"

  - name: ml-pipeline-ui-configmap
    namespace: kubeflow
    behavior: merge
    files:
      - files/viewer-pod-template.json

images:
  - name: gcr.io/ml-pipeline/cache-server
    newName: "ghcr.io/deploykf/kubeflow-pipelines/cache-server"
    newTag: "2.1.0-deploykf.0"
  - name: gcr.io/ml-pipeline/metadata-envoy
    newName: "ghcr.io/deploykf/kubeflow-pipelines/metadata-envoy"
    newTag: "2.1.0-deploykf.0"
  - name: gcr.io/ml-pipeline/metadata-writer
    newName: "ghcr.io/deploykf/kubeflow-pipelines/metadata-writer"
    newTag: "2.1.0-deploykf.0"
  - name: gcr.io/ml-pipeline/api-server
    newName: "ghcr.io/deploykf/kubeflow-pipelines/api-server"
    newTag: "2.1.0-deploykf.0"
  - name: gcr.io/ml-pipeline/persistenceagent
    newName: "ghcr.io/deploykf/kubeflow-pipelines/persistenceagent"
    newTag: "2.1.0-deploykf.0"
  - name: gcr.io/ml-pipeline/scheduledworkflow
    newName: "ghcr.io/deploykf/kubeflow-pipelines/scheduledworkflow"
    newTag: "2.1.0-deploykf.0"
  - name: gcr.io/ml-pipeline/frontend
    newName: "ghcr.io/deploykf/kubeflow-pipelines/frontend"
    newTag: "2.1.0-deploykf.0"
  - name: gcr.io/ml-pipeline/viewer-crd-controller
    newName: "ghcr.io/deploykf/kubeflow-pipelines/viewer-crd-controller"
    newTag: "2.1.0-deploykf.0"
  - name: gcr.io/ml-pipeline/visualization-server
    newName: "ghcr.io/deploykf/kubeflow-pipelines/visualization-server"
    newTag: "2.1.0-deploykf.0"

  ## NOTE: this tag is not aligned to the other KFP images
  - name: gcr.io/tfx-oss-public/ml_metadata_store_server
    newName: "ghcr.io/deploykf/ml_metadata_store_server"
    newTag: "1.14.0-deploykf.0"