apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: katib-ui
  namespace: kubeflow
spec:
  hosts:
    - "deploykf.cloudnative.space"
  gateways:
    - deploykf-istio-gateway/deploykf-gateway
